version: '3.8'
networks:
  backend:
    driver: overlay
  worker:
    driver: overlay
  data:
    driver: overlay

volumes:
  db_data:
  es_data:

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cinelog_db
      POSTGRES_USER: cinelog_user
      POSTGRES_PASSWORD: password123
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - data
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: cinelog_user
      KC_DB_PASSWORD: password123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - backend
      - data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G


  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - backend
      - worker
    ports:
      - "15672:15672"
    deploy:
      replicas: 1


  web:
    image: fynnceapa2/cinelog-backend:latest
    command: sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=cinelog_db
      - DB_USER=cinelog_user
      - DB_PASS=password123
      - OIDC_RP_CLIENT_ID=cinelog_backend
      - OIDC_RP_CLIENT_SECRET=
      - ELASTICSEARCH_HOST=elasticsearch
      - RABBITMQ_HOST=rabbitmq
      - ALLOWED_HOSTS=*
    networks:
      - backend
      - data
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  worker_reviews:
    image: fynnceapa2/cinelog-backend:latest
    command: python manage.py run_review_worker
    environment:
      - DB_HOST=db
      - DB_NAME=cinelog_db
      - DB_USER=cinelog_user
      - DB_PASS=password123
      - RABBITMQ_HOST=rabbitmq
      - ELASTICSEARCH_HOST=elasticsearch
    networks:
      - backend
      - data
      - worker
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  worker_notifications:
    image: fynnceapa2/cinelog-backend:latest
    command: python manage.py run_notification_worker
    environment:
      - RABBITMQ_HOST=rabbitmq
      - EMAIL_HOST=mailhog 
      - EMAIL_PORT=1025
    networks:
      - worker
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  mailhog:
    image: jcalonso/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - worker
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5