"""
Django settings for cinelog project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*3_h8*503=kxy4a(u4*3o-2di#0%pps1$021l)a2^-$n=j!x5u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mozilla_django_oidc',
    'django_elasticsearch_dsl',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cinelog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cinelog.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'cinelog_db'),
        'USER': os.getenv('DB_USER', 'cinelog_user'),
        'PASSWORD': os.getenv('DB_PASS', 'password123'),
        'HOST': os.getenv('DB_HOST', 'db'),
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'core.auth.KeycloakOIDCAuthenticationBackend',
    # 'mozilla_django_oidc.auth.OIDCAuthenticationBackend', # Logare prin Keycloak
    'django.contrib.auth.backends.ModelBackend',  # Fallback (logare clasica admin)
)

OIDC_RP_CLIENT_ID = os.environ.get('OIDC_RP_CLIENT_ID', '420')
OIDC_RP_CLIENT_SECRET = os.environ.get('OIDC_RP_CLIENT_SECRET')
OIDC_RP_SIGN_ALGO = 'RS256'

KEYCLOAK_URL_EXTERNAL = 'http://localhost:8080' # Pentru browser
KEYCLOAK_URL_INTERNAL = 'http://keycloak:8080'  # Pentru comunicarea intre containere

KEYCLOAK_REALM = 'cinelog'

# URL-ul unde utilizatorul este trimis pentru login (Browser -> Localhost)
OIDC_OP_AUTHORIZATION_ENDPOINT = f'{KEYCLOAK_URL_EXTERNAL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/auth'

# URL-ul unde Django cere token-ul (Container -> Container)
OIDC_OP_TOKEN_ENDPOINT = f'{KEYCLOAK_URL_INTERNAL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/token'

# URL-ul pentru informatii utilizator (Container -> Container)
OIDC_OP_USER_ENDPOINT = f'{KEYCLOAK_URL_INTERNAL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/userinfo'

# URL-ul pentru cheile publice (Container -> Container)
OIDC_OP_JWKS_ENDPOINT = f'{KEYCLOAK_URL_INTERNAL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/certs'

# Redirectare dupa login/logout
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


OIDC_OP_LOGOUT_ENDPOINT = f'{KEYCLOAK_URL_EXTERNAL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/logout'

# Unde să ne întoarcem după ce Keycloak ne-a delogat (Homepage-ul nostru)
LOGOUT_REDIRECT_URL_EXTERNAL = 'http://localhost:8000'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


ELASTICSEARCH_DSL = {
    'default': {
        'hosts': 'http://elasticsearch:9200'
    },
}
